FUNCTION "cylPos" : Real
{ S7_Optimized_Access := 'TRUE' }
VERSION : 0.1
   VAR_INPUT 
      sensorAngle : Real;
      sensorAngleOffset : Real;
      pinionModule : Real;
      pinionTeethNum : Real;
   END_VAR


BEGIN
	(*Calcul de la variation relative de position du vérin à partir de la position médiane*)
	#cylPos := (#sensorAngle - #sensorAngleOffset) * #pinionModule * #pinionTeethNum;
END_FUNCTION

